version: '3.8'

services:
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST
      - REDIS_PORT
    env_file:
      - .env
    depends_on:
      - redis
